widht = float(input())
hight = float(input())
consumption = float(input())
V = float(input())
stock = float(input())
answer_one = round(widht*hight,2)
answer_two = round((answer_one + ((stock/100)*answer_one))/consumption,2)
answer_three = int((answer_two // V) + 1)
answer_four = round((answer_three*V) - answer_two,2)
print(answer_one)
print(answer_two)
print(answer_three)
print(answer_four)